package org.snack.irc.handler;

import org.pircbotx.hooks.events.MessageEvent;
import org.snack.irc.main.Monitor;
import org.snack.irc.settings.Config;

public class RomajiHandler implements Runnable {

	private final MessageEvent<?> event;
	private final boolean romaji;

	public RomajiHandler(MessageEvent<?> event, boolean romaji) {
		this.event = event;
		this.romaji = romaji;
	}

	@Override
	public void run() {
		if (romaji) {
			romaji();
		} else {
			katakana();
		}
	}

	/**
	 * Change romaji to katakana
	 */
	private void romaji() {
		String romaji = event.getMessage().substring(9);

		romaji = romaji.replace("ん", "n");
		romaji = romaji.replace("つ", "tsu");
		romaji = romaji.replace("きゃ", "kya");
		romaji = romaji.replace("きゅ", "kyu");
		romaji = romaji.replace("きょ", "kyo");
		romaji = romaji.replace("にゃ", "nya");
		romaji = romaji.replace("にゅ", "nyu");
		romaji = romaji.replace("にょ", "nyo");
		romaji = romaji.replace("しゃ", "sha");
		romaji = romaji.replace("し", "shi");
		romaji = romaji.replace("しゅ", "shu");
		romaji = romaji.replace("しょ", "sho");
		romaji = romaji.replace("ち", "chi");
		romaji = romaji.replace("ちゃ", "cha");
		romaji = romaji.replace("ちゅ", "chu");
		romaji = romaji.replace("ちょ", "cho");
		romaji = romaji.replace("ひゃ", "hya");
		romaji = romaji.replace("ひゅ", "hyu");
		romaji = romaji.replace("ひょ", "hyo");
		romaji = romaji.replace("みゃ", "mya");
		romaji = romaji.replace("みゅ", "myu");
		romaji = romaji.replace("みょ", "myo");
		romaji = romaji.replace("りゃ", "rya");
		romaji = romaji.replace("りゅ", "ryu");
		romaji = romaji.replace("りょ", "ryo");
		romaji = romaji.replace("ぎゃ", "gya");
		romaji = romaji.replace("ぎゅ", "gyu");
		romaji = romaji.replace("ぎょ", "gyo");
		romaji = romaji.replace("びゃ", "bya");
		romaji = romaji.replace("びゅ", "byu");
		romaji = romaji.replace("びょ", "byo");
		romaji = romaji.replace("ぴゃ", "pya");
		romaji = romaji.replace("ぴゅ", "pyu");
		romaji = romaji.replace("ぴょ", "pyo");
		romaji = romaji.replace("じゃ", "ja");
		romaji = romaji.replace("じゅ", "ju");
		romaji = romaji.replace("じょ", "jo");
		romaji = romaji.replace("ば", "ba");
		romaji = romaji.replace("だ", "da");
		romaji = romaji.replace("が", "ga");
		romaji = romaji.replace("は", "ha");
		romaji = romaji.replace("か", "ka");
		romaji = romaji.replace("ま", "ma");
		romaji = romaji.replace("な", "na");
		romaji = romaji.replace("ぱ", "pa");
		romaji = romaji.replace("ら", "ra");
		romaji = romaji.replace("さ", "sa");
		romaji = romaji.replace("た", "ta");
		romaji = romaji.replace("わ", "wa");
		romaji = romaji.replace("や", "ya");
		romaji = romaji.replace("ざ", "za");
		romaji = romaji.replace("あ", "a");
		romaji = romaji.replace("べ", "be");
		romaji = romaji.replace("で", "de");
		romaji = romaji.replace("げ", "ge");
		romaji = romaji.replace("へ", "he");
		romaji = romaji.replace("け", "ke");
		romaji = romaji.replace("め", "me");
		romaji = romaji.replace("ね", "ne");
		romaji = romaji.replace("ぺ", "pe");
		romaji = romaji.replace("れ", "re");
		romaji = romaji.replace("せ", "se");
		romaji = romaji.replace("て", "te");
		romaji = romaji.replace("ゑ", "we");
		romaji = romaji.replace("ぜ", "ze");
		romaji = romaji.replace("え", "e");
		romaji = romaji.replace("び", "bi");
		romaji = romaji.replace("ぎ", "gi");
		romaji = romaji.replace("ひ", "hi");
		romaji = romaji.replace("き", "ki");
		romaji = romaji.replace("み", "mi");
		romaji = romaji.replace("に", "ni");
		romaji = romaji.replace("ぴ", "pi");
		romaji = romaji.replace("り", "ri");
		romaji = romaji.replace("ゐ", "wi");
		romaji = romaji.replace("じ", "ji");
		romaji = romaji.replace("い", "i");
		romaji = romaji.replace("ぼ", "bo");
		romaji = romaji.replace("ど", "do");
		romaji = romaji.replace("ご", "go");
		romaji = romaji.replace("ほ", "ho");
		romaji = romaji.replace("こ", "ko");
		romaji = romaji.replace("も", "mo");
		romaji = romaji.replace("の", "no");
		romaji = romaji.replace("ぽ", "po");
		romaji = romaji.replace("ろ", "ro");
		romaji = romaji.replace("そ", "so");
		romaji = romaji.replace("と", "to");
		romaji = romaji.replace("を", "wo");
		romaji = romaji.replace("よ", "yo");
		romaji = romaji.replace("ぞ", "zo");
		romaji = romaji.replace("お", "o");
		romaji = romaji.replace("ぶ", "bu");
		romaji = romaji.replace("ぐ", "gu");
		romaji = romaji.replace("ふ", "fu");
		romaji = romaji.replace("く", "ku");
		romaji = romaji.replace("む", "mu");
		romaji = romaji.replace("ぬ", "nu");
		romaji = romaji.replace("ぷ", "pu");
		romaji = romaji.replace("る", "ru");
		romaji = romaji.replace("す", "su");
		romaji = romaji.replace("ゆ", "yu");
		romaji = romaji.replace("ず", "zu");
		romaji = romaji.replace("う", "u");
		romaji = romaji.replace("ゔ", "v");
		romaji = romaji.replace("ぢ", "ji");
		romaji = romaji.replace("づ", "zu");
		romaji = romaji.replace("ン", "n");
		romaji = romaji.replace("シ", "shi");
		romaji = romaji.replace("チ", "chi");
		romaji = romaji.replace("ツ", "tsu");
		romaji = romaji.replace("キャ", "kya");
		romaji = romaji.replace("キュ", "kyu");
		romaji = romaji.replace("キョ", "kyo");
		romaji = romaji.replace("ニャ", "nya");
		romaji = romaji.replace("ニュ", "nyu");
		romaji = romaji.replace("ニョ", "nyo");
		romaji = romaji.replace("シャ", "sha");
		romaji = romaji.replace("シュ", "shu");
		romaji = romaji.replace("ショ", "sho");
		romaji = romaji.replace("チャ", "cha");
		romaji = romaji.replace("チュ", "chu");
		romaji = romaji.replace("チョ", "cho");
		romaji = romaji.replace("ヒャ", "hya");
		romaji = romaji.replace("ヒュ", "hyu");
		romaji = romaji.replace("ヒョ", "hyo");
		romaji = romaji.replace("ミャ", "mya");
		romaji = romaji.replace("ミュ", "myu");
		romaji = romaji.replace("ミョ", "myo");
		romaji = romaji.replace("リャ", "rya");
		romaji = romaji.replace("リュ", "ryu");
		romaji = romaji.replace("リョ", "ryo");
		romaji = romaji.replace("ギャ", "gya");
		romaji = romaji.replace("ギュ", "gyu");
		romaji = romaji.replace("ギョ", "gyo");
		romaji = romaji.replace("ビャ", "bya");
		romaji = romaji.replace("ビュ", "byu");
		romaji = romaji.replace("ビョ", "byo");
		romaji = romaji.replace("ピャ", "pya");
		romaji = romaji.replace("ピュ", "pyu");
		romaji = romaji.replace("ピョ", "pyo");
		romaji = romaji.replace("ジャ", "ja");
		romaji = romaji.replace("ジュ", "ju");
		romaji = romaji.replace("ジョ", "jo");
		romaji = romaji.replace("バ", "ba");
		romaji = romaji.replace("ダ", "da");
		romaji = romaji.replace("ガ", "ga");
		romaji = romaji.replace("ハ", "ha");
		romaji = romaji.replace("カ", "ka");
		romaji = romaji.replace("マ", "ma");
		romaji = romaji.replace("ナ", "na");
		romaji = romaji.replace("パ", "pa");
		romaji = romaji.replace("ラ", "ra");
		romaji = romaji.replace("サ", "sa");
		romaji = romaji.replace("タ", "ta");
		romaji = romaji.replace("ワ", "wa");
		romaji = romaji.replace("ヤ", "ya");
		romaji = romaji.replace("ザ", "za");
		romaji = romaji.replace("ア", "a");
		romaji = romaji.replace("ベ", "be");
		romaji = romaji.replace("デ", "de");
		romaji = romaji.replace("ゲ", "ge");
		romaji = romaji.replace("ヘ", "he");
		romaji = romaji.replace("ケ", "ke");
		romaji = romaji.replace("メ", "me");
		romaji = romaji.replace("ネ", "ne");
		romaji = romaji.replace("ペ", "pe");
		romaji = romaji.replace("レ", "re");
		romaji = romaji.replace("セ", "se");
		romaji = romaji.replace("テ", "te");
		romaji = romaji.replace("ヱ", "we");
		romaji = romaji.replace("ゼ", "ze");
		romaji = romaji.replace("エ", "e");
		romaji = romaji.replace("ビ", "bi");
		romaji = romaji.replace("ギ", "gi");
		romaji = romaji.replace("ヒ", "hi");
		romaji = romaji.replace("キ", "ki");
		romaji = romaji.replace("ミ", "mi");
		romaji = romaji.replace("ニ", "ni");
		romaji = romaji.replace("ピ", "pi");
		romaji = romaji.replace("リ", "ri");
		romaji = romaji.replace("ヰ", "wi");
		romaji = romaji.replace("ジ", "ji");
		romaji = romaji.replace("イ", "i");
		romaji = romaji.replace("ボ", "bo");
		romaji = romaji.replace("ド", "do");
		romaji = romaji.replace("ゴ", "go");
		romaji = romaji.replace("ホ", "ho");
		romaji = romaji.replace("コ", "ko");
		romaji = romaji.replace("モ", "mo");
		romaji = romaji.replace("ノ", "no");
		romaji = romaji.replace("ポ", "po");
		romaji = romaji.replace("ロ", "ro");
		romaji = romaji.replace("ソ", "so");
		romaji = romaji.replace("ト", "to");
		romaji = romaji.replace("ヲ", "wo");
		romaji = romaji.replace("ヨ", "yo");
		romaji = romaji.replace("ゾ", "zo");
		romaji = romaji.replace("オ", "o");
		romaji = romaji.replace("ブ", "bu");
		romaji = romaji.replace("グ", "gu");
		romaji = romaji.replace("フ", "fu");
		romaji = romaji.replace("ク", "ku");
		romaji = romaji.replace("ム", "mu");
		romaji = romaji.replace("ヌ", "nu");
		romaji = romaji.replace("プ", "pu");
		romaji = romaji.replace("ル", "ru");
		romaji = romaji.replace("ス", "su");
		romaji = romaji.replace("ユ", "yu");
		romaji = romaji.replace("ズ", "zu");
		romaji = romaji.replace("ウ", "u");
		romaji = romaji.replace("oo", "ō");
		romaji = romaji.replace("ou", "ō");
		romaji = romaji.replace("uu", "ū");

		Monitor.print("~RESPONSE  Romaji: " + event.getMessage().substring(9) + " > " + romaji);
		event.getBot().sendMessage(event.getChannel(), Config.speech.get("RK_ROM").replace("<response>", romaji));
	}

	/**
	 * Change katakana to romaji
	 */
	private void katakana() {
		String katakana = event.getMessage().substring(11);

		katakana = katakana.replace("l", "r");
		katakana = katakana.replace("n", "ン");
		katakana = katakana.replace("shi", "シ");
		katakana = katakana.replace("chi", "チ");
		katakana = katakana.replace("tsu", "ツ");
		katakana = katakana.replace("kya", "キャ");
		katakana = katakana.replace("kyu", "キュ");
		katakana = katakana.replace("kyo", "キョ");
		katakana = katakana.replace("ンya", "ニャ");
		katakana = katakana.replace("ンyu", "ニュ");
		katakana = katakana.replace("ンyo", "ニョ");
		katakana = katakana.replace("sha", "シャ");
		katakana = katakana.replace("shu", "シュ");
		katakana = katakana.replace("sho", "ショ");
		katakana = katakana.replace("cha", "チャ");
		katakana = katakana.replace("chu", "チュ");
		katakana = katakana.replace("cho", "チョ");
		katakana = katakana.replace("hya", "ヒャ");
		katakana = katakana.replace("hyu", "ヒュ");
		katakana = katakana.replace("hyo", "ヒョ");
		katakana = katakana.replace("mya", "ミャ");
		katakana = katakana.replace("myu", "ミュ");
		katakana = katakana.replace("myo", "ミョ");
		katakana = katakana.replace("rya", "リャ");
		katakana = katakana.replace("ryu", "リュ");
		katakana = katakana.replace("ryo", "リョ");
		katakana = katakana.replace("ya", "ギャ");
		katakana = katakana.replace("yu", "ギュ");
		katakana = katakana.replace("yo", "ギョ");
		katakana = katakana.replace("bya", "ビャ");
		katakana = katakana.replace("byu", "ビュ");
		katakana = katakana.replace("byo", "ビョ");
		katakana = katakana.replace("pya", "ピャ");
		katakana = katakana.replace("pyu", "ピュ");
		katakana = katakana.replace("pyo", "ピョ");
		katakana = katakana.replace("ja", "ジャ");
		katakana = katakana.replace("ju", "ジュ");
		katakana = katakana.replace("jo", "ジョ");
		katakana = katakana.replace("ba", "バ");
		katakana = katakana.replace("da", "ダ");
		katakana = katakana.replace("a", "ガ");
		katakana = katakana.replace("ha", "ハ");
		katakana = katakana.replace("ka", "カ");
		katakana = katakana.replace("ma", "マ");
		katakana = katakana.replace("ンa", "ナ");
		katakana = katakana.replace("pa", "パ");
		katakana = katakana.replace("ra", "ラ");
		katakana = katakana.replace("sa", "サ");
		katakana = katakana.replace("ta", "タ");
		katakana = katakana.replace("wa", "ワ");
		katakana = katakana.replace("ya", "ヤ");
		katakana = katakana.replace("za", "ザ");
		katakana = katakana.replace("a", "ア");
		katakana = katakana.replace("be", "ベ");
		katakana = katakana.replace("de", "デ");
		katakana = katakana.replace("e", "ゲ");
		katakana = katakana.replace("he", "ヘ");
		katakana = katakana.replace("ke", "ケ");
		katakana = katakana.replace("me", "メ");
		katakana = katakana.replace("ンe", "ネ");
		katakana = katakana.replace("pe", "ペ");
		katakana = katakana.replace("re", "レ");
		katakana = katakana.replace("se", "セ");
		katakana = katakana.replace("te", "テ");
		katakana = katakana.replace("we", "ヱ");
		katakana = katakana.replace("ze", "ゼ");
		katakana = katakana.replace("e", "エ");
		katakana = katakana.replace("bi", "ビ");
		katakana = katakana.replace("i", "ギ");
		katakana = katakana.replace("hi", "ヒ");
		katakana = katakana.replace("ki", "キ");
		katakana = katakana.replace("mi", "ミ");
		katakana = katakana.replace("ンi", "ニ");
		katakana = katakana.replace("pi", "ピ");
		katakana = katakana.replace("ri", "リ");
		katakana = katakana.replace("wi", "ヰ");
		katakana = katakana.replace("ji", "ジ");
		katakana = katakana.replace("i", "イ");
		katakana = katakana.replace("bo", "ボ");
		katakana = katakana.replace("do", "ド");
		katakana = katakana.replace("o", "ゴ");
		katakana = katakana.replace("ho", "ホ");
		katakana = katakana.replace("ko", "コ");
		katakana = katakana.replace("mo", "モ");
		katakana = katakana.replace("ンo", "ノ");
		katakana = katakana.replace("po", "ポ");
		katakana = katakana.replace("ro", "ロ");
		katakana = katakana.replace("so", "ソ");
		katakana = katakana.replace("to", "ト");
		katakana = katakana.replace("wo", "ヲ");
		katakana = katakana.replace("yo", "ヨ");
		katakana = katakana.replace("zo", "ゾ");
		katakana = katakana.replace("o", "オ");
		katakana = katakana.replace("bu", "ブ");
		katakana = katakana.replace("u", "グ");
		katakana = katakana.replace("fu", "フ");
		katakana = katakana.replace("ku", "ク");
		katakana = katakana.replace("mu", "ム");
		katakana = katakana.replace("ンu", "ヌ");
		katakana = katakana.replace("pu", "プ");
		katakana = katakana.replace("ru", "ル");
		katakana = katakana.replace("su", "ス");
		katakana = katakana.replace("yu", "ユ");
		katakana = katakana.replace("zu", "ズ");
		katakana = katakana.replace("u", "ウ");

		Monitor.print("~RESPONSE  Katakana: " + event.getMessage().substring(11) + " > " + katakana);
		event.getBot().sendMessage(event.getChannel(), Config.speech.get("RK_KAT").replace("<response>", katakana));
	}
}
